# Generated by Django 3.2.3 on 2021-06-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crashreport',
            fields=[
                ('id_crash_report', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=37, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('repair_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crashReport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id_machine', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_service', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'machines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personaldata',
            fields=[
                ('id_personal_data', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('login', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('licenses', models.CharField(blank=True, max_length=22, null=True)),
            ],
            options={
                'db_table': 'personalData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerPosition',
            fields=[
                ('id_worker_position', models.AutoField(primary_key=True, serialize=False)),
                ('worker_position_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'worker_position',
                'managed': False,
            },
        ),
    ]
